[project]
name = "my-ha-eplucon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["dacite>=1.9.2", "homeassistant>=2025.2.5", "orjson>=3.10"]
